// 世界地標資料庫 —— 走到 1 公里內即可蓋章
// [id, 中文名, 英文名, 緯度, 經度, 國家/地區, 大洲, 圖示]
// 介紹文字放在下方的 DESC，每個 id 都必須有一筆，否則建置時就會爆掉

export const CONTINENTS = ['亞洲', '歐洲', '非洲', '北美洲', '南美洲', '大洋洲', '南極洲'];

const RAW = [
  // ── 台灣 ────────────────────────────────────────────
  ['tw-101', '台北 101', 'Taipei 101', 25.0339, 121.5645, '台灣', '亞洲', '🏢'],
  ['tw-cks', '中正紀念堂', 'CKS Memorial Hall', 25.0347, 121.5217, '台灣', '亞洲', '🏛️'],
  ['tw-jiufen', '九份老街', 'Jiufen Old Street', 25.1096, 121.8446, '台灣', '亞洲', '🏮'],
  ['tw-tamsui', '淡水漁人碼頭', 'Tamsui Fisherman’s Wharf', 25.1830, 121.4100, '台灣', '亞洲', '⛵'],
  ['tw-yehliu', '野柳地質公園', 'Yehliu Geopark', 25.2065, 121.6905, '台灣', '亞洲', '🪨'],
  ['tw-sunmoon', '日月潭', 'Sun Moon Lake', 23.8569, 120.9155, '台灣', '亞洲', '🌅'],
  ['tw-alishan', '阿里山', 'Alishan', 23.5108, 120.8017, '台灣', '亞洲', '🚂'],
  ['tw-taroko', '太魯閣峽谷', 'Taroko Gorge', 24.1580, 121.6220, '台灣', '亞洲', '⛰️'],
  ['tw-yushan', '玉山主峰', 'Mt. Jade', 23.4700, 120.9573, '台灣', '亞洲', '🏔️'],
  ['tw-anping', '安平古堡', 'Anping Fort', 23.0015, 120.1607, '台灣', '亞洲', '🏰'],
  ['tw-85', '高雄 85 大樓', 'Tuntex Sky Tower', 22.6117, 120.3006, '台灣', '亞洲', '🌆'],
  ['tw-eluanbi', '鵝鑾鼻燈塔', 'Eluanbi Lighthouse', 21.9018, 120.8536, '台灣', '亞洲', '🗼'],

  // ── 東亞 ────────────────────────────────────────────
  ['jp-tokyotower', '東京鐵塔', 'Tokyo Tower', 35.6586, 139.7454, '日本', '亞洲', '🗼'],
  ['jp-sensoji', '淺草寺', 'Sensō-ji', 35.7148, 139.7967, '日本', '亞洲', '⛩️'],
  ['jp-fuji', '富士山', 'Mt. Fuji', 35.3606, 138.7274, '日本', '亞洲', '🗻'],
  ['jp-fushimi', '伏見稻荷大社', 'Fushimi Inari', 34.9671, 135.7727, '日本', '亞洲', '⛩️'],
  ['jp-kinkakuji', '金閣寺', 'Kinkaku-ji', 35.0394, 135.7292, '日本', '亞洲', '🏯'],
  ['jp-osaka', '大阪城', 'Osaka Castle', 34.6873, 135.5259, '日本', '亞洲', '🏯'],
  ['jp-hiroshima', '原爆圓頂館', 'Hiroshima Peace Dome', 34.3955, 132.4536, '日本', '亞洲', '🕊️'],
  ['jp-sapporo', '札幌時計台', 'Sapporo Clock Tower', 43.0626, 141.3536, '日本', '亞洲', '🕰️'],
  ['kr-gyeongbok', '景福宮', 'Gyeongbokgung', 37.5796, 126.9770, '韓國', '亞洲', '🏯'],
  ['kr-namsan', '首爾 N 塔', 'N Seoul Tower', 37.5512, 126.9882, '韓國', '亞洲', '🗼'],
  ['kr-seongsan', '城山日出峰', 'Seongsan Ilchulbong', 33.4581, 126.9425, '韓國', '亞洲', '🌋'],
  ['cn-greatwall', '萬里長城・八達嶺', 'Great Wall', 40.3587, 116.0075, '中國', '亞洲', '🧱'],
  ['cn-forbidden', '紫禁城', 'Forbidden City', 39.9163, 116.3972, '中國', '亞洲', '🏯'],
  ['cn-terracotta', '兵馬俑', 'Terracotta Army', 34.3841, 109.2785, '中國', '亞洲', '🗿'],
  ['cn-bund', '上海外灘', 'The Bund', 31.2397, 121.4900, '中國', '亞洲', '🌃'],
  ['cn-potala', '布達拉宮', 'Potala Palace', 29.6558, 91.1171, '中國', '亞洲', '🛕'],
  ['cn-zhangjiajie', '張家界', 'Zhangjiajie', 29.3158, 110.4344, '中國', '亞洲', '🏞️'],
  ['hk-victoria', '維多利亞港', 'Victoria Harbour', 22.2940, 114.1722, '香港', '亞洲', '🌉'],
  ['mo-ruins', '大三巴牌坊', 'Ruins of St. Paul’s', 22.1974, 113.5407, '澳門', '亞洲', '⛪'],

  // ── 東南亞 / 南亞 ──────────────────────────────────
  ['kh-angkor', '吳哥窟', 'Angkor Wat', 13.4125, 103.8670, '柬埔寨', '亞洲', '🛕'],
  ['th-grandpalace', '曼谷大皇宮', 'Grand Palace', 13.7500, 100.4914, '泰國', '亞洲', '🏯'],
  ['id-borobudur', '婆羅浮屠', 'Borobudur', -7.6079, 110.2038, '印尼', '亞洲', '🛕'],
  ['id-tanahlot', '海神廟', 'Tanah Lot', -8.6212, 115.0868, '印尼', '亞洲', '🌊'],
  ['sg-mbs', '濱海灣金沙', 'Marina Bay Sands', 1.2834, 103.8607, '新加坡', '亞洲', '🏙️'],
  ['vn-halong', '下龍灣', 'Ha Long Bay', 20.9101, 107.1839, '越南', '亞洲', '⛵'],
  ['my-petronas', '雙子星塔', 'Petronas Towers', 3.1578, 101.7117, '馬來西亞', '亞洲', '🏙️'],
  ['in-taj', '泰姬瑪哈陵', 'Taj Mahal', 27.1751, 78.0421, '印度', '亞洲', '🕌'],
  ['in-varanasi', '瓦拉納西恆河', 'Varanasi Ghats', 25.3109, 83.0104, '印度', '亞洲', '🪔'],
  ['np-everest', '聖母峰基地營', 'Everest Base Camp', 28.0026, 86.8528, '尼泊爾', '亞洲', '🏔️'],

  // ── 中東 ────────────────────────────────────────────
  ['jo-petra', '佩特拉古城', 'Petra', 30.3285, 35.4444, '約旦', '亞洲', '🏛️'],
  ['il-wall', '西牆', 'Western Wall', 31.7767, 35.2345, '以色列', '亞洲', '🕍'],
  ['ae-burj', '哈里發塔', 'Burj Khalifa', 25.1972, 55.2744, '阿聯', '亞洲', '🏙️'],
  ['ir-persepolis', '波斯波利斯', 'Persepolis', 29.9354, 52.8916, '伊朗', '亞洲', '🏛️'],
  ['tr-cappadocia', '卡帕多奇亞', 'Cappadocia', 38.6431, 34.8286, '土耳其', '亞洲', '🎈'],
  ['tr-hagia', '聖索菲亞大教堂', 'Hagia Sophia', 41.0086, 28.9802, '土耳其', '歐洲', '🕌'],

  // ── 歐洲 ────────────────────────────────────────────
  ['fr-eiffel', '艾菲爾鐵塔', 'Eiffel Tower', 48.8584, 2.2945, '法國', '歐洲', '🗼'],
  ['fr-louvre', '羅浮宮', 'Louvre', 48.8606, 2.3376, '法國', '歐洲', '🖼️'],
  ['fr-montsaintmichel', '聖米歇爾山', 'Mont-Saint-Michel', 48.6361, -1.5115, '法國', '歐洲', '🏰'],
  ['uk-bigben', '大笨鐘', 'Big Ben', 51.5007, -0.1246, '英國', '歐洲', '🕰️'],
  ['uk-britishmuseum', '大英博物館', 'British Museum', 51.5194, -0.1270, '英國', '歐洲', '🏛️'],
  ['uk-stonehenge', '巨石陣', 'Stonehenge', 51.1789, -1.8262, '英國', '歐洲', '🗿'],
  ['uk-edinburgh', '愛丁堡城堡', 'Edinburgh Castle', 55.9486, -3.1999, '英國', '歐洲', '🏰'],
  ['ie-moher', '莫赫懸崖', 'Cliffs of Moher', 52.9719, -9.4265, '愛爾蘭', '歐洲', '🌊'],
  ['it-colosseum', '羅馬競技場', 'Colosseum', 41.8902, 12.4922, '義大利', '歐洲', '🏟️'],
  ['it-pisa', '比薩斜塔', 'Leaning Tower of Pisa', 43.7230, 10.3966, '義大利', '歐洲', '🗼'],
  ['it-sanmarco', '聖馬可廣場', 'St. Mark’s Square', 45.4341, 12.3388, '義大利', '歐洲', '🚤'],
  ['it-duomo', '米蘭大教堂', 'Duomo di Milano', 45.4642, 9.1900, '義大利', '歐洲', '⛪'],
  ['va-stpeter', '聖伯多祿大殿', 'St. Peter’s Basilica', 41.9022, 12.4539, '梵蒂岡', '歐洲', '⛪'],
  ['es-sagrada', '聖家堂', 'Sagrada Família', 41.4036, 2.1744, '西班牙', '歐洲', '⛪'],
  ['es-alhambra', '阿爾罕布拉宮', 'Alhambra', 37.1761, -3.5881, '西班牙', '歐洲', '🕌'],
  ['pt-belem', '貝倫塔', 'Belém Tower', 38.6916, -9.2160, '葡萄牙', '歐洲', '🗼'],
  ['de-neuschwanstein', '新天鵝堡', 'Neuschwanstein', 47.5576, 10.7498, '德國', '歐洲', '🏰'],
  ['de-brandenburg', '布蘭登堡門', 'Brandenburg Gate', 52.5163, 13.3777, '德國', '歐洲', '🏛️'],
  ['cz-charles', '查理大橋', 'Charles Bridge', 50.0865, 14.4114, '捷克', '歐洲', '🌉'],
  ['at-schonbrunn', '美泉宮', 'Schönbrunn Palace', 48.1849, 16.3122, '奧地利', '歐洲', '🏰'],
  ['ch-matterhorn', '馬特洪峰', 'Matterhorn', 45.9763, 7.6586, '瑞士', '歐洲', '🏔️'],
  ['ch-jungfrau', '少女峰', 'Jungfrau', 46.5372, 7.9622, '瑞士', '歐洲', '🚠'],
  ['nl-canals', '阿姆斯特丹運河', 'Amsterdam Canals', 52.3667, 4.8945, '荷蘭', '歐洲', '🚲'],
  ['hu-parliament', '布達佩斯國會大廈', 'Hungarian Parliament', 47.5072, 19.0455, '匈牙利', '歐洲', '🏛️'],
  ['ru-stbasil', '聖瓦西里大教堂', 'St. Basil’s Cathedral', 55.7525, 37.6231, '俄羅斯', '歐洲', '⛪'],
  ['gr-santorini', '聖托里尼', 'Santorini', 36.4618, 25.3753, '希臘', '歐洲', '🏖️'],
  ['gr-acropolis', '雅典衛城', 'Acropolis', 37.9715, 23.7257, '希臘', '歐洲', '🏛️'],
  ['is-bluelagoon', '藍湖溫泉', 'Blue Lagoon', 63.8804, -22.4495, '冰島', '歐洲', '♨️'],
  ['no-nordkapp', '北角', 'North Cape', 71.1704, 25.7836, '挪威', '歐洲', '🧭'],
  ['no-geiranger', '蓋朗厄爾峽灣', 'Geirangerfjord', 62.1010, 7.0060, '挪威', '歐洲', '⛰️'],
  ['sj-svalbard', '斯瓦爾巴', 'Svalbard', 78.2232, 15.6469, '挪威', '歐洲', '🐻‍❄️'],

  // ── 非洲 ────────────────────────────────────────────
  ['eg-giza', '吉薩金字塔', 'Pyramids of Giza', 29.9792, 31.1342, '埃及', '非洲', '🔺'],
  ['eg-abusimbel', '阿布辛貝神廟', 'Abu Simbel', 22.3372, 31.6258, '埃及', '非洲', '🗿'],
  ['ma-merzouga', '撒哈拉・梅爾祖卡', 'Merzouga, Sahara', 31.0819, -4.0088, '摩洛哥', '非洲', '🐪'],
  ['ma-marrakech', '馬拉喀什老城', 'Marrakech Medina', 31.6295, -7.9811, '摩洛哥', '非洲', '🕌'],
  ['zw-victoria', '維多利亞瀑布', 'Victoria Falls', -17.9243, 25.8572, '辛巴威', '非洲', '💦'],
  ['tz-kilimanjaro', '吉力馬札羅山', 'Mt. Kilimanjaro', -3.0674, 37.3556, '坦尚尼亞', '非洲', '🏔️'],
  ['tz-serengeti', '塞倫蓋提', 'Serengeti', -2.3333, 34.8333, '坦尚尼亞', '非洲', '🦁'],
  ['za-capepoint', '好望角', 'Cape of Good Hope', -34.3568, 18.4740, '南非', '非洲', '🌊'],
  ['za-tablemountain', '桌山', 'Table Mountain', -33.9628, 18.4098, '南非', '非洲', '⛰️'],
  ['mg-baobab', '猴麵包樹大道', 'Avenue of the Baobabs', -20.2506, 44.4183, '馬達加斯加', '非洲', '🌳'],
  ['na-sossusvlei', '索蘇斯黎沙丘', 'Sossusvlei', -24.7276, 15.3444, '納米比亞', '非洲', '🏜️'],

  // ── 北美洲 ──────────────────────────────────────────
  ['us-liberty', '自由女神像', 'Statue of Liberty', 40.6892, -74.0445, '美國', '北美洲', '🗽'],
  ['us-timessquare', '時代廣場', 'Times Square', 40.7580, -73.9855, '美國', '北美洲', '🌃'],
  ['us-goldengate', '金門大橋', 'Golden Gate Bridge', 37.8199, -122.4783, '美國', '北美洲', '🌉'],
  ['us-grandcanyon', '大峽谷', 'Grand Canyon', 36.1069, -112.1129, '美國', '北美洲', '🏜️'],
  ['us-yellowstone', '老忠實間歇泉', 'Old Faithful', 44.4605, -110.8281, '美國', '北美洲', '💨'],
  ['us-yosemite', '優勝美地', 'Yosemite', 37.7456, -119.5936, '美國', '北美洲', '🏞️'],
  ['us-niagara', '尼加拉瀑布', 'Niagara Falls', 43.0828, -79.0742, '美國', '北美洲', '💦'],
  ['us-whitehouse', '白宮', 'White House', 38.8977, -77.0365, '美國', '北美洲', '🏛️'],
  ['us-hollywood', '好萊塢標誌', 'Hollywood Sign', 34.1341, -118.3215, '美國', '北美洲', '🎬'],
  ['us-vegas', '拉斯維加斯大道', 'Las Vegas Strip', 36.1147, -115.1728, '美國', '北美洲', '🎰'],
  ['us-denali', '迪納利峰', 'Denali', 63.0692, -151.0070, '美國', '北美洲', '🏔️'],
  ['ca-louise', '露易絲湖', 'Lake Louise', 51.4254, -116.1773, '加拿大', '北美洲', '🏞️'],
  ['ca-cntower', '加拿大國家電視塔', 'CN Tower', 43.6426, -79.3871, '加拿大', '北美洲', '🗼'],
  ['mx-chichen', '奇琴伊察', 'Chichén Itzá', 20.6843, -88.5678, '墨西哥', '北美洲', '🔺'],
  ['mx-teotihuacan', '特奧蒂瓦坎', 'Teotihuacán', 19.6925, -98.8438, '墨西哥', '北美洲', '🌞'],
  ['cu-havana', '哈瓦那舊城', 'Old Havana', 23.1136, -82.3666, '古巴', '北美洲', '🚗'],

  // ── 南美洲 ──────────────────────────────────────────
  ['pe-machupicchu', '馬丘比丘', 'Machu Picchu', -13.1631, -72.5450, '秘魯', '南美洲', '🏔️'],
  ['br-christ', '救世基督像', 'Christ the Redeemer', -22.9519, -43.2105, '巴西', '南美洲', '🗿'],
  ['br-iguazu', '伊瓜蘇瀑布', 'Iguazú Falls', -25.6953, -54.4367, '巴西', '南美洲', '💦'],
  ['br-amazon', '亞馬遜・瑪瑙斯', 'Amazon, Manaus', -3.1190, -60.0217, '巴西', '南美洲', '🌴'],
  ['bo-uyuni', '烏尤尼鹽沼', 'Salar de Uyuni', -20.1338, -67.4891, '玻利維亞', '南美洲', '🧂'],
  ['cl-torres', '百內國家公園', 'Torres del Paine', -50.9423, -72.9877, '智利', '南美洲', '⛰️'],
  ['cl-easter', '復活節島', 'Easter Island', -27.1127, -109.3497, '智利', '南美洲', '🗿'],
  ['ec-galapagos', '加拉巴哥群島', 'Galápagos', -0.7437, -90.3136, '厄瓜多', '南美洲', '🐢'],
  ['ar-perito', '佩里托莫雷諾冰川', 'Perito Moreno Glacier', -50.4967, -73.1377, '阿根廷', '南美洲', '🧊'],

  // ── 大洋洲 ──────────────────────────────────────────
  ['au-opera', '雪梨歌劇院', 'Sydney Opera House', -33.8568, 151.2153, '澳洲', '大洋洲', '🎭'],
  ['au-uluru', '烏魯魯', 'Uluru', -25.3444, 131.0369, '澳洲', '大洋洲', '🪨'],
  ['au-reef', '大堡礁', 'Great Barrier Reef', -16.7000, 145.9000, '澳洲', '大洋洲', '🐠'],
  ['nz-milford', '米佛峽灣', 'Milford Sound', -44.6414, 167.8974, '紐西蘭', '大洋洲', '⛰️'],
  ['nz-hobbiton', '哈比村', 'Hobbiton', -37.8721, 175.6829, '紐西蘭', '大洋洲', '🏡'],
  ['pf-borabora', '波拉波拉島', 'Bora Bora', -16.5004, -151.7415, '法屬玻里尼西亞', '大洋洲', '🏝️'],
  ['fj-fiji', '斐濟', 'Fiji', -17.7134, 178.0650, '斐濟', '大洋洲', '🌺'],

  // ── 南極洲 ──────────────────────────────────────────
  ['aq-peninsula', '南極半島', 'Antarctic Peninsula', -64.0000, -61.0000, '南極', '南極洲', '🐧'],
  ['aq-southpole', '阿蒙森－史考特南極站', 'South Pole Station', -90.0000, 0.0000, '南極', '南極洲', '🧭'],
];



// 國家/地區的英文名。資料檔存的是中文，英文語系與搜尋都靠這張表。
const COUNTRY_EN = {
  '台灣': 'Taiwan',
  '日本': 'Japan',
  '韓國': 'South Korea',
  '中國': 'China',
  '香港': 'Hong Kong',
  '澳門': 'Macau',
  '柬埔寨': 'Cambodia',
  '泰國': 'Thailand',
  '印尼': 'Indonesia',
  '新加坡': 'Singapore',
  '越南': 'Vietnam',
  '馬來西亞': 'Malaysia',
  '印度': 'India',
  '尼泊爾': 'Nepal',
  '約旦': 'Jordan',
  '以色列': 'Israel',
  '阿聯': 'UAE',
  '伊朗': 'Iran',
  '土耳其': 'Türkiye',
  '法國': 'France',
  '英國': 'United Kingdom',
  '愛爾蘭': 'Ireland',
  '義大利': 'Italy',
  '梵蒂岡': 'Vatican City',
  '西班牙': 'Spain',
  '葡萄牙': 'Portugal',
  '德國': 'Germany',
  '捷克': 'Czechia',
  '奧地利': 'Austria',
  '瑞士': 'Switzerland',
  '荷蘭': 'Netherlands',
  '匈牙利': 'Hungary',
  '俄羅斯': 'Russia',
  '希臘': 'Greece',
  '冰島': 'Iceland',
  '挪威': 'Norway',
  '埃及': 'Egypt',
  '摩洛哥': 'Morocco',
  '辛巴威': 'Zimbabwe',
  '坦尚尼亞': 'Tanzania',
  '南非': 'South Africa',
  '馬達加斯加': 'Madagascar',
  '納米比亞': 'Namibia',
  '美國': 'United States',
  '加拿大': 'Canada',
  '墨西哥': 'Mexico',
  '古巴': 'Cuba',
  '秘魯': 'Peru',
  '巴西': 'Brazil',
  '玻利維亞': 'Bolivia',
  '智利': 'Chile',
  '厄瓜多': 'Ecuador',
  '阿根廷': 'Argentina',
  '澳洲': 'Australia',
  '紐西蘭': 'New Zealand',
  '法屬玻里尼西亞': 'French Polynesia',
  '斐濟': 'Fiji',
  '南極': 'Antarctica',
};

// 每個地標的介紹。與名稱一樣，中文語系顯示 zh、其他語系顯示 en。
const DESC = {
  'tw-101': ['508 公尺，2004 至 2010 年間的世界第一高樓。外型取自竹節，樓頂懸著一顆 660 噸的調諧質量阻尼器抵抗颱風與地震。',
    'At 508 m it was the world\'s tallest building from 2004 to 2010. Its bamboo-inspired tiers hide a 660-tonne tuned mass damper that steadies it against typhoons and quakes.'],
  'tw-cks': ['1980 年落成，白牆藍瓦。正堂前的 89 級台階對應蔣中正逝世時的年歲，廣場兩側是國家戲劇院與音樂廳。',
    'Completed in 1980. The 89 steps up to the main hall match Chiang Kai-shek\'s age at death; the National Theater and Concert Hall flank the plaza.'],
  'tw-jiufen': ['日治時期因金礦而興起的山城。石階窄巷與紅燈籠沿著山壁層層而上，可遠眺基隆山與東北角海岸。',
    'A hillside town that boomed on gold mining under Japanese rule. Red lanterns line stone stairways climbing the slope, with the sea beyond.'],
  'tw-tamsui': ['淡水河出海口的漁港。白色斜張的「情人橋」跨過港區，是台北近郊最有名的看夕陽地點之一。',
    'A fishing harbour at the mouth of the Tamsui River. The white cable-stayed Lover\'s Bridge crosses the basin; a favourite sunset spot near Taipei.'],
  'tw-yehliu': ['突出海中的岬角，砂岩經海蝕與風化刻成蕈狀岩、薑石與燭台石，最有名的是頸子越來越細的「女王頭」。',
    'A cape where sea and wind have carved sandstone into mushroom rocks and candlestick formations — the best known is the Queen\'s Head.'],
  'tw-sunmoon': ['台灣最大的天然湖泊，海拔約 750 公尺。北側形如日輪、南側如彎月而得名，也是邵族的傳統領域。',
    'Taiwan\'s largest natural lake, about 750 m above sea level. Named for its round northern half and crescent southern one; homeland of the Thao people.'],
  'tw-alishan': ['以日出、雲海、晚霞、森林與高山鐵路聞名。森林鐵路自嘉義爬升逾 2,000 公尺，一路穿越熱帶到溫帶林相。',
    'Known for its sunrises, seas of cloud and forest railway, which climbs over 2,000 m from Chiayi through tropical to temperate forest.'],
  'tw-taroko': ['立霧溪在大理岩層中下切而成的峽谷，谷壁近乎垂直，最窄處僅數公尺寬。中橫公路沿著谷壁開鑿而過。',
    'A gorge cut by the Liwu River through marble. Its walls rise almost vertically and close to just a few metres apart in places.'],
  'tw-yushan': ['海拔 3,952 公尺，台灣與整個東北亞的第一高峰。冬季山頂積雪，登頂需事先申請入園。',
    'At 3,952 m, the highest peak in Taiwan and in all of Northeast Asia. Snow covers the summit in winter.'],
  'tw-anping': ['1624 年荷蘭東印度公司所建熱蘭遮城的舊址，是台灣最早的西式城堡。現場仍留有部分原始外牆遺構。',
    'The site of Fort Zeelandia, built by the Dutch East India Company from 1624 — Taiwan\'s earliest European fortress. Sections of the original wall survive.'],
  'tw-85': ['高 347.5 公尺，外型取自「高」字。74 樓的觀景台可以俯瞰整座高雄港與市區。',
    '347.5 m tall, its outline shaped like the Chinese character for “high”. The 74th-floor observatory overlooks Kaohsiung Harbour.'],
  'tw-eluanbi': ['台灣最南端岬角上的燈塔，1883 年啟用。因早年守塔人屢遭襲擊，塔身圍有壕溝與槍眼，是世界少見的武裝燈塔。',
    'A lighthouse on Taiwan\'s southern tip, lit in 1883. After attacks on its keepers it was ringed with a moat and gun ports — a rare armed lighthouse.'],
  'jp-tokyotower': ['1958 年完工，高 333 公尺，比艾菲爾鐵塔還高 13 公尺。原本是電波塔，橘白相間的塗裝是航空法規的要求。',
    'Completed in 1958 at 333 m — 13 m taller than the Eiffel Tower. Built as a broadcast mast; its orange-and-white paint is required by aviation rules.'],
  'jp-sensoji': ['東京最古老的寺院，相傳創建於 628 年。雷門的大紅燈籠與通往本堂的仲見世商店街是淺草的標誌。',
    'Tokyo\'s oldest temple, traditionally founded in 628. The giant lantern of Kaminarimon and the Nakamise shopping street lead to the main hall.'],
  'jp-fuji': ['海拔 3,776 公尺的活火山，日本最高峰。最近一次噴發是 1707 年的寶永大噴火，2013 年列入世界文化遺產。',
    'An active volcano and Japan\'s highest peak at 3,776 m. It last erupted in 1707, and became a World Heritage site in 2013.'],
  'jp-fushimi': ['稻荷信仰的總本宮。山道上約一萬座朱紅鳥居連成隧道，每一座都是信眾或企業奉納的。',
    'The head shrine of Inari. Around ten thousand vermilion torii, each donated by a worshipper or business, form tunnels up the hillside.'],
  'jp-kinkakuji': ['正式名稱鹿苑寺，上兩層樓貼滿金箔。現存的建築是 1950 年遭縱火燒毀後，於 1955 年重建的。',
    'Formally Rokuon-ji, its upper two floors covered in gold leaf. The present pavilion is a 1955 rebuild after arson destroyed it in 1950.'],
  'jp-osaka': ['豐臣秀吉於 1583 年始建，歷經多次焚毀與重建。現在的天守閣是 1931 年以鋼筋混凝土重建，內部作為博物館。',
    'First built by Toyotomi Hideyoshi from 1583 and destroyed and rebuilt several times. The present keep is a 1931 concrete reconstruction housing a museum.'],
  'jp-hiroshima': ['1945 年 8 月 6 日，原子彈在這棟建築上空約 600 公尺爆炸。殘存的骨架與圓頂被原樣保留，作為那一天的見證。',
    'The bomb detonated some 600 m above this building on 6 August 1945. Its skeletal frame and dome were left exactly as they stood, as a witness to that day.'],
  'jp-sapporo': ['1878 年建的美式木造建築，原是札幌農學校的演武場。塔上的機械鐘至今仍靠重錘驅動，準點報時。',
    'An 1878 American-style wooden hall, originally a drill hall for Sapporo Agricultural College. Its weight-driven clock still strikes the hour.'],
  'kr-gyeongbok': ['朝鮮王朝 1395 年所建的正宮，壬辰倭亂中焚毀，19 世紀重建。光化門前每日舉行守門將換崗儀式。',
    'The main palace of the Joseon dynasty, founded in 1395, burned in the 1590s and rebuilt in the 19th century. Guards change ceremonially at Gwanghwamun.'],
  'kr-namsan': ['立於南山之上，塔高 236 公尺，加上山勢後塔頂約在海拔 480 公尺。觀景台可以環看整個首爾盆地。',
    'Standing on Namsan, the 236 m tower puts its top about 480 m above sea level. The observatory takes in the whole Seoul basin.'],
  'kr-seongsan': ['約 5,000 年前海底火山噴發形成的凝灰岩丘，火山口直徑約 600 公尺，是濟州島最有名的看日出地點。',
    'A tuff cone thrown up by an undersea eruption about 5,000 years ago. Its crater is some 600 m across — Jeju\'s most famous sunrise spot.'],
  'cn-greatwall': ['明長城保存最完整、也最早開放的一段，位於北京西北的軍都山。牆體隨山脊起伏，最陡處坡度超過 40 度。',
    'The best-preserved and first-opened stretch of the Ming wall, in the hills northwest of Beijing. It rides the ridgeline, pitching over 40 degrees in places.'],
  'cn-forbidden': ['明清兩代的皇宮，1420 年建成，佔地 72 萬平方公尺、現存房屋約 8,700 間，是世界上規模最大的木構宮殿群。',
    'The imperial palace of the Ming and Qing, completed in 1420. It covers 72 hectares with some 8,700 rooms — the largest surviving wooden palace complex.'],
  'cn-terracotta': ['1974 年農民打井時意外挖到，是秦始皇陵的陪葬坑。已出土逾 8,000 尊陶俑，每一尊的面容都不相同。',
    'Found by farmers digging a well in 1974, part of the burial complex of China\'s first emperor. Over 8,000 figures have been unearthed — no two faces alike.'],
  'cn-bund': ['黃浦江西岸長約 1.5 公里的江堤，沿線 52 棟建築橫跨新古典與裝飾藝術等風格，對岸是陸家嘴的天際線。',
    'A 1.5 km waterfront on the Huangpu, lined with 52 buildings in neoclassical and art deco styles, facing the towers of Pudong.'],
  'cn-potala': ['建在海拔 3,700 公尺的紅山之上，7 世紀始建、17 世紀大規模擴建。主體高 115 公尺，共 13 層。',
    'Rising on Red Hill at 3,700 m. First built in the 7th century and greatly expanded in the 17th, its main structure stands 115 m over 13 storeys.'],
  'cn-zhangjiajie': ['石英砂岩峰林地貌，逾 3,000 根石柱拔地而起，最高的超過 300 公尺，常年被雲霧繞著。',
    'A forest of quartz-sandstone pillars — more than 3,000 of them, the tallest over 300 m, usually wrapped in cloud.'],
  'hk-victoria': ['亞洲主要的天然深水港之一，兩岸摩天樓密集。每晚八點有「幻彩詠香江」燈光音樂表演。',
    'One of Asia\'s great natural deep-water harbours, walled in by skyscrapers. A light and sound show runs along both shores each evening at eight.'],
  'mo-ruins': ['聖保祿教堂 1602 至 1640 年建成，1835 年大火後只剩下花崗岩前壁與 68 級石階，雕飾融合了歐洲與東方元素。',
    'All that survives of St Paul\'s church (1602–1640) after an 1835 fire: the granite façade and 68 steps, carved with both European and Asian motifs.'],
  'kh-angkor': ['12 世紀吳哥王朝所建，原為印度教毗濕奴神廟，後來改為佛寺。護城河每邊長逾 1.5 公里，是世界最大的宗教建築群。',
    'Built in the 12th century as a Hindu temple to Vishnu, later Buddhist. Its moat runs over 1.5 km a side — the largest religious monument on earth.'],
  'th-grandpalace': ['1782 年隨曼谷建都而興建，曾是暹羅王室的居所。宮內的玉佛寺供奉一尊由整塊翡翠雕成的佛像。',
    'Begun in 1782 when Bangkok became the capital, and long the royal residence. Within it, Wat Phra Kaew houses a Buddha carved from a single block of jade.'],
  'id-borobudur': ['9 世紀的大乘佛教遺跡，由九層平台構成一座巨大的曼陀羅，牆面共有 2,672 塊浮雕與 504 尊佛像。',
    'A 9th-century Mahayana monument laid out as a giant mandala of nine terraces, carrying 2,672 relief panels and 504 Buddha statues.'],
  'id-tanahlot': ['建在潮間帶岩礁上的峇里島神廟。漲潮時與陸地完全隔開，只有退潮時才能走過去。',
    'A Balinese temple perched on a tidal rock. At high tide it is cut off from land; you can only walk out at low water.'],
  'sg-mbs': ['三座塔樓頂上架著一艘船形的空中花園，長 340 公尺，邊緣是一座 150 公尺長的無邊際泳池。',
    'Three towers carrying a 340 m ship-shaped SkyPark, with a 150 m infinity pool along its edge.'],
  'vn-halong': ['石灰岩海灣，約 1,600 座石灰岩島嶼與石柱散布其中，多數因為太過陡峭而無人居住。',
    'A bay scattered with some 1,600 limestone islands and pillars, most of them too steep for anyone to live on.'],
  'my-petronas': ['高 452 公尺，1998 至 2004 年間是世界最高建築。41 與 42 樓之間有一座雙層空中橋樑相連。',
    '452 m tall, and the world\'s tallest building from 1998 to 2004. A double-decker skybridge links the towers at the 41st and 42nd floors.'],
  'in-taj': ['蒙兀兒皇帝沙賈汗為愛妃慕塔芝‧瑪哈所建的陵墓，1632 年動工，耗時逾 20 年。白色大理石在不同光線下會變換色調。',
    'A mausoleum raised by the Mughal emperor Shah Jahan for his wife Mumtaz Mahal, begun in 1632 and over 20 years in the making. Its marble shifts colour with the light.'],
  'in-varanasi': ['世界上持續有人居住最久的城市之一。恆河西岸排列著八十餘座石階碼頭，印度教徒在此沐浴、祭祀與火葬。',
    'One of the world\'s longest continuously inhabited cities. Over eighty stone ghats line the Ganges, used for bathing, ritual and cremation.'],
  'np-everest': ['南側基地營位於海拔約 5,364 公尺的昆布冰川旁，是攀登聖母峰的起點，本身也是熱門的健行終點。',
    'The south base camp sits at about 5,364 m beside the Khumbu Glacier — the starting point for Everest climbs and a trekking destination in itself.'],
  'jo-petra': ['納巴泰人在砂岩峭壁上鑿出的城市，約始於西元前後。要經過一條長約 1.2 公里的狹縫峽谷「蛇道」才能進入。',
    'A Nabataean city carved into sandstone cliffs around the turn of the first millennium, reached through the Siq, a 1.2 km slot canyon.'],
  'il-wall': ['第二聖殿外圍擋土牆殘存的一段，希律王時期所建，是猶太教最重要的祈禱場所。',
    'A surviving section of the retaining wall of the Second Temple, built under Herod — the most important place of prayer in Judaism.'],
  'ae-burj': ['高 828 公尺，2010 年啟用至今仍是世界第一高樓。共 163 層，平面形狀取自沙漠花卉蜘蛛蘭。',
    'At 828 m, the tallest building in the world since it opened in 2010. Its 163-storey floor plan is based on the desert flower Hymenocallis.'],
  'ir-persepolis': ['阿契美尼德帝國的禮儀首都，西元前 518 年由大流士一世下令興建，西元前 330 年被亞歷山大焚毀，留下石階與列柱。',
    'The ceremonial capital of the Achaemenid empire, begun by Darius I around 518 BC and burned by Alexander in 330 BC. Its stairways and columns still stand.'],
  'tr-cappadocia': ['火山灰凝固成的軟岩經侵蝕形成「仙人煙囪」。居民自古在岩體中鑿出住居與地下城，現在以熱氣球聞名。',
    'Wind and water have carved soft volcanic tuff into “fairy chimneys”. People hollowed homes and whole underground cities from the rock; now famous for balloon flights.'],
  'tr-hagia': ['537 年落成時是世界最大的教堂，1453 年後改為清真寺，1935 至 2020 年間是博物館。巨大穹頂直徑約 31 公尺。',
    'The largest church in the world when finished in 537, a mosque after 1453, and a museum from 1935 to 2020. Its dome spans about 31 m.'],
  'fr-eiffel': ['為 1889 年世界博覽會而建，高 330 公尺。原訂展覽結束後拆除，因為當作無線電天線很好用而保留下來。',
    'Built for the 1889 World\'s Fair and 330 m tall. It was meant to be dismantled afterwards, but survived because it made such a useful radio mast.'],
  'fr-louvre': ['由中世紀城堡改建的王宮，1793 年開放為博物館。館藏逾 30 萬件，庭院中的玻璃金字塔是 1989 年才加上的。',
    'A medieval fortress that became a royal palace, then a museum in 1793. It holds over 300,000 works; the glass pyramid was added in 1989.'],
  'fr-montsaintmichel': ['建在潮汐灘地岩島上的修道院，8 世紀始建。此處潮差可達 14 公尺，漲潮時整座島與陸地隔開。',
    'An abbey on a tidal island, founded in the 8th century. Tides here range up to 14 m, cutting the island off from land at high water.'],
  'uk-bigben': ['「大笨鐘」原本指的是鐘樓裡那口重 13.7 噸的大鐘。塔身高 96 公尺，2012 年正式命名為伊麗莎白塔。',
    '“Big Ben” is properly the 13.7-tonne bell inside. The 96 m tower itself was renamed the Elizabeth Tower in 2012.'],
  'uk-britishmuseum': ['1753 年創立，是世界上第一座公共的國家博物館。館藏約 800 萬件，長年免費開放。',
    'Founded in 1753 as the world\'s first public national museum. Its collection runs to some eight million objects, and entry has always been free.'],
  'uk-stonehenge': ['約在西元前 3000 至 2000 年間分階段豎立，最大的立石重逾 25 噸。主軸線對準夏至日出與冬至日落。',
    'Raised in stages between about 3000 and 2000 BC, its largest stones weighing over 25 tonnes. Its axis lines up with midsummer sunrise and midwinter sunset.'],
  'uk-edinburgh': ['建在死火山頸的城堡岩上，考古顯示此地至少自鐵器時代就有人居住。每年八月在城前廣場舉行軍樂節。',
    'Set on Castle Rock, the plug of an extinct volcano, and occupied since at least the Iron Age. The Military Tattoo fills its esplanade each August.'],
  'ie-moher': ['大西洋岸的頁岩與砂岩懸崖，綿延約 14 公里，最高處約 214 公尺，也是重要的海鳥繁殖地。',
    'Shale and sandstone cliffs running about 14 km along the Atlantic, rising to some 214 m, and a major seabird breeding site.'],
  'it-colosseum': ['西元 80 年啟用的圓形競技場，可容納 5 至 8 萬名觀眾。地板下有供野獸與角鬥士上場的通道與升降機關。',
    'An amphitheatre opened in AD 80 for 50,000 to 80,000 spectators. Beneath the floor ran passages and lifts for animals and gladiators.'],
  'it-pisa': ['1173 年動工，因為地基土層鬆軟，還在施工中就開始傾斜。1990 年代整治後，傾角穩定在約 4 度。',
    'Begun in 1173, it started leaning during construction on soft ground. Stabilisation work in the 1990s left it tilted about four degrees.'],
  'it-sanmarco': ['威尼斯唯一稱作 piazza 的廣場。東側是聖馬可大教堂與 98.6 公尺高的鐘樓，冬季常因高潮位而積水。',
    'The only square in Venice called a piazza. St Mark\'s Basilica and its 98.6 m campanile close the east end; winter high tides often flood it.'],
  'it-duomo': ['1386 年動工，歷時近六百年才完成，是義大利最大的教堂。屋頂上林立著 135 座尖塔與約 3,400 尊雕像。',
    'Begun in 1386 and nearly six centuries in the building, Italy\'s largest cathedral bristles with 135 spires and some 3,400 statues.'],
  'va-stpeter': ['1626 年祝聖，米開朗基羅設計的穹頂高 136 公尺。教堂建在傳統認為是聖伯多祿墓地的位置上。',
    'Consecrated in 1626, with Michelangelo\'s dome rising 136 m. It stands over what tradition holds to be the tomb of St Peter.'],
  'es-sagrada': ['高第 1883 年接手的教堂，至今仍在興建中。結構取法自然界的樹幹與骨骼，尖塔全部完成後將成為世界最高的教堂。',
    'Gaudí took charge in 1883 and it is still unfinished. Its structure borrows from trees and bone; once the towers are done it will be the tallest church in the world.'],
  'es-alhambra': ['13 至 14 世紀納斯里王朝的宮殿城堡群，以幾何裝飾、鐘乳石狀穹頂與庭園水景著稱。',
    'A palace-fortress of the Nasrid dynasty from the 13th and 14th centuries, famed for its geometric ornament, honeycomb vaults and water gardens.'],
  'pt-belem': ['1519 年完工的曼努埃爾式防禦塔，扼守太加斯河口，是大航海時代船隻出發與歸來時的地標。',
    'A Manueline fort completed in 1519 guarding the mouth of the Tagus — the landmark ships passed leaving and returning in the age of discovery.'],
  'de-neuschwanstein': ['巴伐利亞國王路德維希二世 1869 年起建的浪漫主義城堡，他去世時仍未完工。山下的瑪麗恩橋可以遠眺全景。',
    'A romantic castle begun in 1869 for Ludwig II of Bavaria and left unfinished at his death. Marienbrücke below gives the classic view.'],
  'de-brandenburg': ['1791 年落成的新古典主義城門，門頂是一座四馬戰車雕像。冷戰期間，它就夾在柏林圍牆的無人地帶裡。',
    'A neoclassical gate finished in 1791, crowned by a quadriga. Through the Cold War it stood stranded in the no-man\'s land beside the Wall.'],
  'cz-charles': ['1357 年由查理四世下令興建，橋長約 516 公尺。兩側欄杆上立著 30 座巴洛克風格的聖人雕像。',
    'Commissioned by Charles IV in 1357 and about 516 m long, its parapets lined with 30 baroque statues of saints.'],
  'at-schonbrunn': ['哈布斯堡王朝的夏宮，共 1,441 個房間。園中的動物園創於 1752 年，是世界現存最古老的動物園。',
    'The Habsburgs\' summer palace, with 1,441 rooms. The zoo in its grounds, founded in 1752, is the oldest still operating anywhere.'],
  'ch-matterhorn': ['海拔 4,478 公尺，四面稜線構成近乎金字塔的形狀。1865 年首登，下山時繩索斷裂，四名隊員罹難。',
    '4,478 m high, its four ridges meeting in an almost perfect pyramid. First climbed in 1865 — four of the party died when a rope broke on the way down.'],
  'ch-jungfrau': ['海拔 4,158 公尺。少女峰鐵道鑿穿艾格峰與僧侶峰，通往海拔 3,454 公尺的歐洲最高火車站。',
    '4,158 m high. A railway tunnelled through the Eiger and Mönch reaches Europe\'s highest station at 3,454 m.'],
  'nl-canals': ['17 世紀黃金時代開鑿的同心圓運河網，總長逾 100 公里、有 1,500 多座橋。沿岸房屋因為地基木樁下沉，多半微微傾斜。',
    'A ring of canals dug in the 17th-century Golden Age — over 100 km of water and more than 1,500 bridges, lined by houses leaning on their timber piles.'],
  'hu-parliament': ['1904 年完工，長 268 公尺，是匈牙利最大的建築。圓頂高 96 公尺，呼應建國的西元 896 年。',
    'Finished in 1904 and 268 m long, Hungary\'s largest building. Its dome stands 96 m high, echoing the year 896 of the country\'s founding.'],
  'ru-stbasil': ['1561 年為紀念攻下喀山而建，由九座禮拜堂組成。彩色洋蔥頂那身鮮豔配色，其實是 17 世紀之後才慢慢加上的。',
    'Completed in 1561 to mark the capture of Kazan, and really nine chapels in one. The bright colours of its onion domes were only added from the 17th century on.'],
  'gr-santorini': ['約西元前 1600 年一場巨大火山噴發後留下的破火山口。白牆藍頂的村落，沿著 300 公尺高的崖頂而建。',
    'The rim of a caldera left by a huge eruption around 1600 BC. Whitewashed villages cling to cliffs some 300 m above the sea.'],
  'gr-acropolis': ['西元前 5 世紀的城邦聖域。帕德嫩神廟的柱子刻意做成中央微凸，用來抵銷視覺上會顯得下凹的錯覺。',
    'The sacred citadel of 5th-century BC Athens. The Parthenon\'s columns swell slightly at the middle to cancel the eye\'s illusion that they sag.'],
  'is-bluelagoon': ['鄰近地熱發電廠的人工潟湖，水溫維持在約 38 度。乳藍色來自水中溶解的矽酸鹽。',
    'A man-made lagoon beside a geothermal plant, held at about 38 °C. Its milky blue comes from silica dissolved in the water.'],
  'no-nordkapp': ['北緯 71 度的懸崖岬角，常被稱作歐洲大陸最北點。五月中到七月底，太陽整日不落。',
    'A cliff headland at 71° N, often called the northernmost point of mainland Europe. From mid-May to late July the sun never sets.'],
  'no-geiranger': ['長約 15 公里的峽灣，兩岸崖壁高逾千公尺，「七姊妹」等瀑布直落水面。',
    'A 15 km fjord walled by cliffs over a thousand metres high, with waterfalls such as the Seven Sisters dropping straight into the water.'],
  'sj-svalbard': ['北緯 74 至 81 度之間的群島，北極熊的數量與居民人數相當。島上設有全球種子庫，保存各國作物種原。',
    'An archipelago between 74° and 81° N, with roughly as many polar bears as people. It holds the global seed vault.'],
  'eg-giza': ['古夫金字塔約在西元前 2560 年建成，原高 146.6 公尺，是古代世界七大奇蹟中唯一留存至今的。',
    'The Great Pyramid, finished around 2560 BC, originally stood 146.6 m — the only one of the seven ancient wonders still standing.'],
  'eg-abusimbel': ['拉美西斯二世於西元前 13 世紀開鑿的岩窟神廟。1960 年代為了避開亞斯文水壩的淹沒，整座被切塊搬遷、上移了 65 公尺。',
    'Rock temples cut for Ramesses II in the 13th century BC. In the 1960s the whole complex was sawn into blocks and moved 65 m higher to escape the Aswan dam.'],
  'ma-merzouga': ['撒哈拉西緣的沙丘群，最高的爾格謝比沙丘超過 150 公尺，這座村子是進入沙漠的常見起點。',
    'Dunes on the western edge of the Sahara. Erg Chebbi rises over 150 m, and the village is a common gateway into the desert.'],
  'ma-marrakech': ['紅土城牆環繞的舊城。中心的傑馬艾夫納廣場一入夜，就成為攤販、樂手與說書人的市集。',
    'A walled old town built of red earth. Its Jemaa el-Fnaa square fills each evening with food stalls, musicians and storytellers.'],
  'zw-victoria': ['尚比西河跌入寬約 1,700 公尺、深逾 100 公尺的裂谷。水霧可以升到數百公尺高，當地稱它「雷鳴之煙」。',
    'The Zambezi drops into a chasm 1,700 m wide and over 100 m deep. The spray rises hundreds of metres — locally, “the smoke that thunders”.'],
  'tz-kilimanjaro': ['海拔 5,895 公尺，非洲最高峰，也是世界最高的獨立山體。山頂終年有冰川，但正在快速消退。',
    'At 5,895 m, Africa\'s highest peak and the tallest free-standing mountain in the world. Its summit glaciers are shrinking fast.'],
  'tz-serengeti': ['草原生態系。每年約 150 萬頭牛羚與數十萬斑馬跟著雨季遷徙，是地表規模最大的陸生動物遷徙。',
    'Grassland where some 1.5 million wildebeest and hundreds of thousands of zebra follow the rains — the largest land migration on earth.'],
  'za-capepoint': ['1488 年迪亞士繞過此處，開啟歐洲通往印度的航路。它並不是非洲最南端，最南點是東南方的厄加勒斯角。',
    'Rounded by Bartolomeu Dias in 1488, opening the sea route to India. It is not Africa\'s southernmost point — that is Cape Agulhas, to the southeast.'],
  'za-tablemountain': ['頂部平坦、長約 3 公里的砂岩台地，海拔 1,086 公尺。山頂常蓋著一層被稱作「桌布」的雲。',
    'A flat sandstone plateau about 3 km long and 1,086 m high. A cloud layer known as the “tablecloth” often spills over its edge.'],
  'mg-baobab': ['穆隆達瓦附近的土路兩旁立著數十棵猴麵包樹，樹齡可達八百年。它們是周圍原始森林被開墾後留下來的。',
    'Dozens of baobabs, some up to 800 years old, line a dirt road near Morondava — survivors of the forest that was cleared around them.'],
  'na-sossusvlei': ['納米比沙漠中的鹽土窪地，周圍紅色沙丘高逾 300 公尺。鄰近的死亡谷裡，駱駝刺樹已經枯立了好幾百年。',
    'A salt pan ringed by red dunes over 300 m tall. In nearby Deadvlei, camel thorn trees have stood dead for centuries.'],
  'us-liberty': ['法國於 1886 年贈予美國，連基座高 93 公尺。銅製外皮因為氧化，從原本的棕色轉成現在的青綠色。',
    'A gift from France in 1886, standing 93 m with its pedestal. Its copper skin oxidised from brown to the green it is today.'],
  'us-timessquare': ['百老匯與第七大道交會處，1904 年隨《紐約時報》遷入而改名。這裡的分區法規反過來要求建築必須設置大型廣告招牌。',
    'Where Broadway crosses Seventh Avenue, renamed in 1904 when the New York Times moved in. Zoning here actually requires buildings to carry bright signage.'],
  'us-goldengate': ['1937 年通車，主跨 1,280 公尺，當時是世界最長的懸索橋。橘紅色塗裝是為了在濃霧中維持能見度。',
    'Opened in 1937 with a 1,280 m main span, then the longest suspension bridge in the world. Its orange paint keeps it visible in the fog.'],
  'us-grandcanyon': ['科羅拉多河切穿高原而成，長 446 公里、最深達 1,857 公尺，崖壁露出近 20 億年的地層。',
    'Cut by the Colorado River — 446 km long and up to 1,857 m deep, its walls exposing nearly two billion years of rock.'],
  'us-yellowstone': ['因為噴發間隔規律而得名，平均約每 90 分鐘噴一次，水柱高 30 至 55 公尺。',
    'Named for how regularly it erupts — roughly every 90 minutes, throwing water 30 to 55 m into the air.'],
  'us-yosemite': ['冰河作用刻出的花崗岩谷地。酋長岩是世界最大的花崗岩獨石之一，垂直落差約 900 公尺。',
    'A granite valley shaped by glaciers. El Capitan is one of the largest granite monoliths on earth, with about 900 m of vertical rock.'],
  'us-niagara': ['由三段瀑布組成，其中馬蹄瀑布寬約 790 公尺。水量最大時，每秒有超過 2,800 立方公尺的水落下。',
    'Three falls together; the Horseshoe alone is about 790 m wide, carrying over 2,800 cubic metres a second at peak flow.'],
  'us-whitehouse': ['1800 年起成為美國總統官邸，1814 年英軍縱火後重建。共 132 個房間，部分區域對外開放參觀。',
    'The president\'s residence since 1800, rebuilt after British troops burned it in 1814. It has 132 rooms, some open to visitors.'],
  'us-hollywood': ['1923 年設立時原本是房地產廣告，寫的是「HOLLYWOODLAND」，1949 年才拆去後半段。每個字母高約 14 公尺。',
    'Put up in 1923 as a property advert reading “HOLLYWOODLAND”; the last four letters came down in 1949. Each letter stands about 14 m tall.'],
  'us-vegas': ['長約 6.8 公里的大道，兩側是複製威尼斯、巴黎、金字塔等主題的大型度假村。',
    'A 6.8 km boulevard lined with resorts that copy Venice, Paris and the pyramids.'],
  'us-denali': ['海拔 6,190 公尺，北美最高峰。從山腳算起的相對高差比聖母峰還大，2015 年正式改回原住民語的名字。',
    'At 6,190 m, the highest peak in North America. Its rise from base to summit is greater than Everest\'s, and it officially regained its Native name in 2015.'],
  'ca-louise': ['冰川融水形成的湖，湖水因為懸浮的岩粉散射光線而呈藍綠色，背後就是維多利亞冰川。',
    'A glacier-fed lake whose turquoise comes from rock flour suspended in the water, with the Victoria Glacier behind it.'],
  'ca-cntower': ['高 553 公尺，1975 至 2007 年間是世界最高的自立建築。342 公尺處設有一段玻璃地板。',
    '553 m tall, and the world\'s tallest free-standing structure from 1975 to 2007. A glass floor sits at 342 m.'],
  'mx-chichen': ['馬雅城市遺址，主神廟卡斯蒂略金字塔共有 365 級台階。春分與秋分時，階梯側面的光影會形成一條羽蛇下降的形狀。',
    'A Maya city whose main pyramid has 365 steps. At the equinoxes, light and shadow form a serpent descending its staircase.'],
  'mx-teotihuacan': ['西元前 100 年至西元 550 年間的大城，全盛時期人口逾十萬。太陽金字塔高約 65 公尺。',
    'A city that flourished from about 100 BC to AD 550, home to over 100,000 people. The Pyramid of the Sun stands some 65 m high.'],
  'cu-havana': ['16 世紀的西班牙殖民城區，廣場、教堂與柱廊街道大致保持原貌，街上仍跑著 1950 年代的美國老車。',
    'A 16th-century Spanish colonial quarter of squares, churches and colonnaded streets — still driven by American cars from the 1950s.'],
  'pe-machupicchu': ['15 世紀的印加城市，建在海拔 2,430 公尺的山脊上。石牆切得極為精密，完全不用灰漿，1911 年才為外界所知。',
    'A 15th-century Inca settlement on a ridge at 2,430 m. Its stones are cut so precisely they need no mortar; the outside world learned of it in 1911.'],
  'br-christ': ['1931 年落成，像高 30 公尺、基座 8 公尺，張開的雙臂寬 28 公尺，立在 700 公尺高的科科瓦多山頂。',
    'Unveiled in 1931: a 30 m figure on an 8 m base, arms spanning 28 m, on top of the 700 m Corcovado.'],
  'br-iguazu': ['由 275 道瀑布組成，沿著邊緣綿延近 3 公里。最壯觀的「魔鬼咽喉」是一個 U 形深谷。',
    'Some 275 separate falls spread over nearly 3 km. The most dramatic of them, the Devil\'s Throat, is a U-shaped chasm.'],
  'br-amazon': ['亞馬遜河中游的城市，鄰近黑河與索利蒙伊斯河的匯流處。兩條河因為水色與溫度不同，並流數公里都不相混。',
    'A city on the middle Amazon, near where the Rio Negro meets the Solimões. Differing in colour and temperature, the two run side by side for kilometres without mixing.'],
  'bo-uyuni': ['世界最大的鹽沼，面積逾 10,000 平方公里。雨季積起一層薄水後，整片鹽沼成為反射天空的鏡面。',
    'The world\'s largest salt flat, over 10,000 km². In the wet season a thin film of water turns the whole thing into a mirror.'],
  'cl-torres': ['巴塔哥尼亞的國家公園，三座花崗岩尖塔拔起於冰河湖之上。天氣多變，強風幾乎終年不斷。',
    'A Patagonian park where three granite towers rise above glacial lakes, under famously changeable weather and near-constant wind.'],
  'cl-easter': ['距離最近的有人島嶼超過 1,900 公里，是世界上最偏遠的有人島之一。島上約有 900 尊摩艾石像。',
    'Over 1,900 km from the nearest inhabited island, among the most remote places people live. About 900 moai stand on it.'],
  'ec-galapagos': ['赤道上的火山群島。1835 年達爾文在此注意到雀鳥與陸龜隨島嶼而不同，成為天擇理論的線索。',
    'Volcanic islands on the equator, where in 1835 Darwin noticed how finches and tortoises differed from island to island.'],
  'ar-perito': ['面積約 250 平方公里，冰壁高出湖面約 70 公尺。前緣會定期崩解落水，而且它是少數沒有持續退縮的大冰川。',
    'About 250 km² of ice, its face rising some 70 m above the lake. Chunks calve off regularly — and unusually, it is not in retreat.'],
  'au-opera': ['1973 年落成，屋頂是由一百萬片瑞典瓷磚鋪成的殼狀結構。設計者烏松在完工之前就辭職離開了。',
    'Opened in 1973, its shells clad in a million Swedish tiles. Its architect, Jørn Utzon, resigned before it was finished.'],
  'au-uluru': ['高出地面 348 公尺的砂岩巨岩，露出的其實只是地下岩體的一小部分。它是阿南古人的聖地，2019 年起禁止攀爬。',
    'A sandstone monolith 348 m above the plain — and mostly still underground. Sacred to the Anangu, it has been closed to climbers since 2019.'],
  'au-reef': ['由約 2,900 個珊瑚礁組成，綿延 2,300 公里，是地球上最大的珊瑚礁系統。',
    'Some 2,900 reefs stretching 2,300 km — the largest coral reef system on earth.'],
  'nz-milford': ['冰河切鑿而成的峽灣，米特峰自水面直立 1,692 公尺。年雨量逾 6,000 毫米，一下雨崖壁上滿是瀑布。',
    'A glacier-carved fjord where Mitre Peak rises 1,692 m straight from the water. Over 6,000 mm of rain a year fills the cliffs with waterfalls.'],
  'nz-hobbiton': ['《魔戒》與《哈比人》的外景地，位在一座綿羊牧場中。拍攝結束後保留了 44 個哈比人洞屋。',
    'The film set for the Shire, built on a working sheep farm. Forty-four hobbit holes were left standing after shooting wrapped.'],
  'pf-borabora': ['火山島被淺礁湖與環礁圍著。中央的奧特馬努山高 727 公尺，是古火山口殘餘的部分。',
    'A volcanic island ringed by a shallow lagoon and barrier reef. Mount Otemanu, 727 m, is what remains of its crater.'],
  'fj-fiji': ['由逾 330 座島嶼組成的南太平洋島國，其中約三分之一有人居住。180 度經線穿過境內，但國際換日線為了統一日期而繞了開來。',
    'A Pacific nation of over 330 islands, about a third of them inhabited. The 180th meridian runs through it, though the date line detours to keep one date.'],
  'aq-peninsula': ['南極洲最北、也最溫暖的一部分，朝著南美方向伸出去。它是全球升溫最快的地區之一，也是絕大多數觀光船的目的地。',
    'The northernmost and mildest part of Antarctica, reaching towards South America. It is warming faster than almost anywhere else, and is where nearly all ships go.'],
  'aq-southpole': ['位於地理南極的研究站，海拔約 2,835 公尺，年均溫約攝氏 -49 度。站體建在可以頂升的支柱上，以免被積雪埋住。',
    'A research station at the geographic South Pole, 2,835 m up, averaging about −49 °C. It stands on jackable stilts to stay above the drifting snow.'],
};

export const LANDMARKS = RAW.map(([id, zh, en, lat, lng, country, continent, icon]) =>
  ({ id, zh, en, lat, lng, country, continent, icon,
     countryEn: COUNTRY_EN[country], descZh: DESC[id][0], descEn: DESC[id][1] }));

export const LANDMARKS_BY_ID = new Map(LANDMARKS.map((l) => [l.id, l]));

/** 蓋章半徑（公尺） */
export const VISIT_RADIUS_M = 1000;
